apiVersion: v1
kind: Secret
metadata:
  name: server-secret
  namespace: crs
type: Opaque
stringData:
  GMAIL_USER: meetjakasaniya24@gmail.com
  GMAIL_PASS: fdmxblmuzbjwcehj
  JWT_SECRET: meetjakasaniyakisecretkeyhai6782
  IMAGEKIT_PRIVATE_KEY: private_eAqhSaW2yR1WV7XpSUI5+RiHOlg=

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: server-config
  namespace: crs
data:
  FRONTEND_URL: http://client-service:80
  IMAGEKIT_PUBLIC_KEY: public_XVhKeElnZl/CO3n4Q1oU2Z+nPt8=
  IMAGEKIT_URL_ENDPOINT: https://ik.imagekit.io/Meet6782

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  namespace: crs
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      name: server
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: hetgajera01/car-rental-server:latest
          envFrom:
	    - configMapRef:
	       name: server-config
	    - secretRef:
	       name: server-secret
	  ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: crs
spec:
  selector:
    app: server
  ports:
    - port: 3000
      protocol: TCP 
      targetPort: 3000

