apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  namespace: crs
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: hetgajera01/car-rental-client:latest
          env:
            - name: VITE_CURRENCY
              value: '₹'
            - name: VITE_BASE_URL
              value: "http://server-service:3000"
          ports:
            - containerPort: 5173

