apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  namespace: crs
  labels:
    app: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      name: server
      labels:
        app: server
    spec:
      containers:
        - name: server
          image: hetgajera01/car-rental-server:latest
          envFrom:
            - configMapRef:
                name: server-config
            - secretRef:
                name: server-secret
          ports:
            - containerPort: 3000

